### ISSUE TITLE
add service group

### ISSUE THREAD

**Issue by TakesxiSximada** [TakesxiSximada/docker-volume#13]
```
volumes:
  nginx:
    lib:
      hostpath: ${here}/volumes/${service}
      vboxpath: /var/lib/${project}/${service}
      directory:
        - ${here}/volumes/${name}/etc/nginx/conf.d

  app:
    src:
      hostpath: ${here}/${service}
      vboxpath: /var/src/${project}/${service}

    lib:
      hostpath: ${here}/volumes/${service}
      vboxpath: /var/lib/${project}/${service}
      directory:
        - ${here}/volumes/${name}/var/lib/mysql
        - ${here}/volumes/${name}/var/log/mysql

  mysql-master:
    lib:
      hostpath: ${here}/volumes/${service}
      vboxpath: /var/lib/${project}/${service}
      uid: 999
      gid: 999
      directory:
        - ${here}/volumes/${service}/etc/mysql/conf.d
        - ${here}/volumes/${service}/var/lib/mysql
        - ${here}/volumes/${service}/var/log/mysql

  mysql-ro-a:
    lib:
      hostpath: ${here}/volumes/${service}
      vboxpath: /var/lib/${project}/${service}
      uid: 999
      gid: 999
      directory:
        - ${here}/volumes/${service}/etc/mysql/conf.d
        - ${here}/volumes/${service}/var/lib/mysql
        - ${here}/volumes/${service}/var/log/mysql

  mysql-ro-b:
    lib:
      hostpath: ${here}/volumes/${service}
      vboxpath: /var/lib/${project}/${service}
      uid: 999
      gid: 999
      directory:
        - ${here}/volumes/${service}/etc/mysql/conf.d
        - ${here}/volumes/${service}/var/lib/mysql
        - ${here}/volumes/${service}/var/log/mysql
$
```
